AWSTemplateFormatVersion: 2010-09-09
Description: Private Pipeline setup

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Git Rep Configuration"
        Parameters:
          - ConnectionARN
          - Repo
          - Branch
    ParameterLabels:
      ConnectionARN:
        default: Connection ARN
      Repo:
        default: Git Repository
      Branch:
        default: Git Branch

Parameters:
  # GIT SETUP
  ConnectionARN:
    Description: Github Connection ARN
    Type: String

  Repo:
    Description: Github repo for project
    Type: String
    Default: "EIGTech/cfn-log-retention-policy"

  Branch:
    Description: Github branch name to use
    Type: String
    Default: "main"

Resources:
  ############
  # PIPELINE #
  ############
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref "ArtifactStoreBucket"
        Type: S3
      Name: !Ref AWS::StackName
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Name: GitHubSource
          Actions:
            - Name: Source
              RunOrder: 1
              InputArtifacts: []
              ActionTypeId:
                Version: "1"
                Owner: AWS
                Category: Source
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Ref ConnectionARN
                FullRepositoryId: !Ref Repo
                BranchName: !Ref Branch
                OutputArtifactFormat: "CODE_ZIP"
              OutputArtifacts:
                - Name: SourceCode

        - Name: Build
          Actions:
            - Name: Build
              RunOrder: 1
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildProject
              OutputArtifacts:
                - Name: BuildArtifact

        - Name: Deploy
          Actions:
            - Name: CreateChangeset
              RunOrder: 1
              InputArtifacts:
                - Name: BuildArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !GetAtt CFNRole.Arn
                StackName: FN-LogRetentionPolicy
                ChangeSetName: pipeline-changeset
                TemplatePath: BuildArtifact::post-template.yaml

            - Name: ExecuteDevelopChangeset
              RunOrder: 2
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: !GetAtt CFNRole.Arn
                StackName: FN-LogRetentionPolicy
                ChangeSetName: pipeline-changeset

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: Allow
            Principal:
              Service: [codepipeline.amazonaws.com]
        Version: "2012-10-17"
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "s3:*"
                  - "cloudformation:CreateStack"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:DeleteChangeSet"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:SetStackPolicy"
                  - "iam:PassRole"
                  - "sns:Publish"
                  - "codedeploy:*"
                  - "codebuild:*"
                  - "codestar:*"
                  - "codestar-connections:*"
                  - "lambda:*"
                Effect: Allow
                Resource: "*"

  ###################
  # CLOUD FORMATION #
  ###################
  CFNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: Allow
            Principal:
              Service: [cloudformation.amazonaws.com]
        Version: "2012-10-17"
      Path: /
      Policies:
        - PolicyName: CloudFormationRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "*"
                Effect: Allow
                Resource: "*"

  ##############
  # CODE BUILD #
  ##############
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: S3_BUCKET
            Value: !Ref ArtifactStoreBucket
      Name: !Ref AWS::StackName
      ServiceRole: !GetAtt CodeBuildRole.Arn

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

###########
# OUTPUTS #
###########
Outputs:
  Pipeline:
    Description: Pipeline for deployment
    Value: !Ref Pipeline
    Export:
      Name: !Sub ${AWS::StackName}-Pipeline
