AWSTemplateFormatVersion: "2010-09-09"

Transform:
  - AWS::Serverless-2016-10-31

Description: CloudFormation resource to define CloudWatch Logs retention policies

Resources:
  LogRetentionPolicyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      Description: CloudFormation resource for CloudWatch Logs retention policies
      CodeUri: ../.rollup/resource.zip
      Handler: resource.handler
      FunctionName: LogRetentionPolicy
      Policies:
        - Statement:
            - Sid: ResumeQueue
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:DeleteRetentionPolicy
                - logs:DescribeLogGroups
                - logs:PutRetentionPolicy
              Resource: "*"

  LogRetentionPolicy:
    Type: Custom::LogRetentionPolicy
    Properties:
      ServiceToken: !GetAtt LogRetentionPolicyFunction.Arn
      LogGroup: !Sub /aws/lambda/${LogRetentionPolicyFunction}
      RetentionInDays: 7

Outputs:
  FunctionArn:
    Value: !GetAtt LogRetentionPolicyFunction.Arn
    Export:
      Name: CFN-LogRetentionPolicy
